// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251207234416_UpdateMovieImageFile")]
    partial class UpdateMovieImageFile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomerMovie", b =>
                {
                    b.Property<int>("CustomersId")
                        .HasColumnType("integer");

                    b.Property<int>("MoviesId")
                        .HasColumnType("integer");

                    b.HasKey("CustomersId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("CustomerMovies", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Changes")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("WebApplication1.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsSubscribed")
                        .HasColumnType("boolean");

                    b.Property<int>("MembershipTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MembershipTypeId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsSubscribed = true,
                            MembershipTypeId = 1,
                            Name = "Alice Dupont"
                        },
                        new
                        {
                            Id = 2,
                            IsSubscribed = false,
                            MembershipTypeId = 2,
                            Name = "Karim Ben Ali"
                        },
                        new
                        {
                            Id = 3,
                            IsSubscribed = true,
                            MembershipTypeId = 3,
                            Name = "Sophie Martin"
                        },
                        new
                        {
                            Id = 4,
                            IsSubscribed = false,
                            MembershipTypeId = 4,
                            Name = "Amine Trabelsi"
                        },
                        new
                        {
                            Id = 5,
                            IsSubscribed = true,
                            MembershipTypeId = 2,
                            Name = "Lina Haddad"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sci-Fi"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.MembershipType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscountRate")
                        .HasColumnType("integer");

                    b.Property<string>("DurationInMonth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SignUpFee")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MembershipTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscountRate = 0,
                            DurationInMonth = "1 Month",
                            SignUpFee = 0
                        },
                        new
                        {
                            Id = 2,
                            DiscountRate = 10,
                            DurationInMonth = "3 Months",
                            SignUpFee = 30
                        },
                        new
                        {
                            Id = 3,
                            DiscountRate = 15,
                            DurationInMonth = "6 Months",
                            SignUpFee = 90
                        },
                        new
                        {
                            Id = 4,
                            DiscountRate = 25,
                            DurationInMonth = "1 Year",
                            SignUpFee = 150
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateAjoutMovie")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageFile")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreId = 4,
                            ImageFile = "inception.jpeg",
                            Name = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            GenreId = 2,
                            ImageFile = "jurassic.jpeg",
                            Name = "Jurassic World"
                        },
                        new
                        {
                            Id = 3,
                            GenreId = 1,
                            ImageFile = "91qMS2JSdhL._AC_UF1000,1000_QL80_.jpg",
                            Name = "Bella"
                        },
                        new
                        {
                            Id = 4,
                            GenreId = 1,
                            ImageFile = "pridePrejudice.jpeg",
                            Name = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 5,
                            GenreId = 4,
                            ImageFile = "matrix.jpeg",
                            Name = "The Matrix"
                        },
                        new
                        {
                            Id = 6,
                            GenreId = 2,
                            ImageFile = "hangover.jpeg",
                            Name = "The Hangover"
                        },
                        new
                        {
                            Id = 7,
                            GenreId = 3,
                            ImageFile = "it.jpeg",
                            Name = "It"
                        },
                        new
                        {
                            Id = 8,
                            GenreId = 1,
                            ImageFile = "titanic.jpeg",
                            Name = "Titanic"
                        },
                        new
                        {
                            Id = 9,
                            GenreId = 4,
                            ImageFile = "endgame.jpeg",
                            Name = "Avengers: Endgame"
                        },
                        new
                        {
                            Id = 10,
                            GenreId = 2,
                            ImageFile = "jumanji.jpeg",
                            Name = "Jumanji"
                        });
                });

            modelBuilder.Entity("CustomerMovie", b =>
                {
                    b.HasOne("WebApplication1.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication1.Models.Customer", b =>
                {
                    b.HasOne("WebApplication1.Models.MembershipType", "MembershipType")
                        .WithMany("Customers")
                        .HasForeignKey("MembershipTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MembershipType");
                });

            modelBuilder.Entity("WebApplication1.Models.Movie", b =>
                {
                    b.HasOne("WebApplication1.Models.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("WebApplication1.Models.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("WebApplication1.Models.MembershipType", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
