// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251023221004_UpdateMoviesSeed")]
    partial class UpdateMoviesSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("WebApplication1.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sci-Fi"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreId = 4,
                            ImageUrl = "/images/images.jpeg",
                            Name = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            GenreId = 2,
                            ImageUrl = "/images/eyJidWNrZXQiOiJmcm9udGllci1jbXMiLCJrZXkiOiIyMDI1LTA1L2p3ZTMta2V5YXJ0XzE5MjB4MTA4MF8zNDJ2bmYzdjg5cTcuanBnIiwiZWRpdHMiOnsid2VicCI6eyJxdWFsaXR5Ijo4NX0sInRvRm9ybWF0Ijoid2VicCJ9fQ==.webp",
                            Name = "Jurassic World"
                        },
                        new
                        {
                            Id = 3,
                            GenreId = 1,
                            ImageUrl = "/images/91qMS2JSdhL._AC_UF1000,1000_QL80_.jpg",
                            Name = "Bella"
                        },
                        new
                        {
                            Id = 4,
                            GenreId = 1,
                            ImageUrl = "/images/2420938.avif",
                            Name = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 5,
                            GenreId = 4,
                            ImageUrl = "/images/matrix.jpeg",
                            Name = "The Matrix"
                        },
                        new
                        {
                            Id = 6,
                            GenreId = 2,
                            ImageUrl = "/images/hangover.jpeg",
                            Name = "The Hangover"
                        },
                        new
                        {
                            Id = 7,
                            GenreId = 3,
                            ImageUrl = "/images/it.jpeg",
                            Name = "It"
                        },
                        new
                        {
                            Id = 8,
                            GenreId = 1,
                            ImageUrl = "/images/titanic.jpeg",
                            Name = "Titanic"
                        },
                        new
                        {
                            Id = 9,
                            GenreId = 4,
                            ImageUrl = "/images/endgame.jpeg",
                            Name = "Avengers: Endgame"
                        },
                        new
                        {
                            Id = 10,
                            GenreId = 2,
                            ImageUrl = "/images/jumanji.jpeg",
                            Name = "Jumanji"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Movie", b =>
                {
                    b.HasOne("WebApplication1.Models.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("WebApplication1.Models.Genre", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
